version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"  # Agent receives traces
      - "6831:6831/udp"  # Agent receives traces
      - "6832:6832/udp"  # Agent receives traces
      - "5778:5778"      # Agent config HTTP endpoint
      - "16686:16686"    # UI access
      - "14268:14268"    # HTTP trace submission
      - "9411:9411"      # Zipkin compatibility
    networks:
      - jaeger-network

  pg:
    image: postgres:latest
    container_name: pg
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=jaeger
      - POSTGRES_PASSWORD=jaeger
    volumes:
      - jaeger-volume:/var/lib/postgresql/data
    ports:
      - 5934:5432

  pgadmin4: 
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jaeger@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports: 
      - 5933:80
    networks: 
      - jaeger-network
    depends_on:
      - pg

networks:
  jaeger-network:
    driver: bridge

volumes:
  jaeger-volume:
    driver: local